apiVersion: v1
kind: Pod
metadata:
  name: app-config-consumer
spec:
  containers:
  - name: config-app
    image: busybox
    command: ["sh", "-c", "env | grep APP_; echo DB_PASSWORD=$DB_PASSWORD; sleep 3600"]
    envFrom:
    - configMapRef:
        name: app-config
    - secretRef:
        name: app-secret
