apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-resilience-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-resilience-demo
  template:
    metadata:
      labels:
        app: nginx-resilience-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
